name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # in intial commit is set to v1 because I want to test also the dependabot
    - uses: actions/checkout@v4
    - name: Deploy to GitHub Pages
      # in intial commit is set to v3 because I want to test also the dependabot
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
          publish_branch: gh-pages
          publish_dir: ./deploy
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}