name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # in intial commit is set to v1 because I want to test also the dependabot
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        python hello.py